[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "*", features = ["derive"] }
thiserror = "*"
toml = "*"
tracing = "*"
tracing-subscriber = "*"
winit = "*"
